version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unparam

  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
