version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam

settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
