//go:build ignore

// gen_parameters generates parameters_ncep.go from data/ncep_gribtable.txt,
// which is wgrib2's table of parameter names (src/gribtables/ncep/gribtable
// in https://github.com/NOAA-EMC/wgrib2). Using the same table means that
// squall's parameter names match wgrib2's.
//
// Each line of the table has the fields
//
//	discipline:mtab_set:mtab_low:mtab_high:center:local_table:category:number:name:description:units
//
// Entries with center 0 are the WMO standard parameters; those with center 7
// and local table 1 are NCEP's local parameters. As in wgrib2, the first
// entry for a parameter takes precedence.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
)

type entry struct {
	key                     [3]uint8
	name, description, unit string
}

func main() {
	f, err := os.Open("data/ncep_gribtable.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	wmo := map[[3]uint8]entry{}
	ncep := map[[3]uint8]entry{}
	sc := bufio.NewScanner(f)
	for line := 1; sc.Scan(); line++ {
		fields := strings.Split(sc.Text(), ":")
		if len(fields) < 11 {
			log.Fatalf("line %d: expected 11 fields, got %d", line, len(fields))
		}
		var v [8]int
		for i := range v {
			if v[i], err = strconv.Atoi(fields[i]); err != nil {
				log.Fatalf("line %d: %v", line, err)
			}
		}
		disc, center, localTable, cat, num := v[0], v[4], v[5], v[6], v[7]
		e := entry{
			key:         [3]uint8{uint8(disc), uint8(cat), uint8(num)},
			name:        fields[8],
			description: strings.Join(fields[9:len(fields)-1], ":"),
			unit:        fields[len(fields)-1],
		}
		var m map[[3]uint8]entry
		switch {
		case center == 0:
			m = wmo
		case center == 7 && localTable == 1:
			m = ncep
		default:
			continue
		}
		if _, ok := m[e.key]; !ok {
			m[e.key] = e
		}
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by gen_parameters.go from data/ncep_gribtable.txt; DO NOT EDIT.\n\n")
	b.WriteString("package tables\n\n")
	write := func(name, doc string, m map[[3]uint8]entry) {
		keys := make([][3]uint8, 0, len(m))
		for k := range m {
			keys = append(keys, k)
		}
		slices.SortFunc(keys, func(a, b [3]uint8) int {
			return int(a[0])<<16 + int(a[1])<<8 + int(a[2]) - (int(b[0])<<16 + int(b[1])<<8 + int(b[2]))
		})
		fmt.Fprintf(&b, "// %s\nvar %s = map[[3]uint8]Parameter{\n", doc, name)
		for _, k := range keys {
			e := m[k]
			fmt.Fprintf(&b, "\t{%d, %d, %d}: {%q, %q, %q},\n", k[0], k[1], k[2], e.name, e.description, e.unit)
		}
		b.WriteString("}\n\n")
	}
	write("wmoParameters", "wmoParameters holds the WMO standard parameters, keyed by {discipline, category, number}.", wmo)
	write("ncepLocalParameters", "ncepLocalParameters holds NCEP's local parameters, keyed as wmoParameters is.", ncep)

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("parameters_ncep.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
