// Code generated from wgrib2 3.8.0 src/Level.c (https://github.com/NOAA-EMC/wgrib2); DO NOT EDIT.

package tables

// The level descriptions of Code Table 4.5 that wgrib2 uses, as printf-style formats
// where %g is the level value. The local entries are indexed by type-192.

// wgrib2Levels are the WMO level types 0-191.
var wgrib2Levels = [...]string{
	0:   "reserved",
	1:   "surface",
	2:   "cloud base",
	3:   "cloud top",
	4:   "0C isotherm",
	5:   "level of adiabatic condensation from sfc",
	6:   "max wind",
	7:   "tropopause",
	8:   "top of atmosphere",
	9:   "sea bottom",
	10:  "entire atmosphere",
	11:  "cumulonimbus base",
	12:  "cumulonimbus top",
	13:  "lowest level %g%% integrated cloud cover",
	14:  "level of free convection",
	15:  "convection condensation level",
	16:  "level of neutral buoyancy",
	17:  "Departure level of most unstable parcel of air (MUDL)",
	18:  "Departure level of mixed layer parcel of air with specified layer depth %g (Pa)",
	19:  "reserved",
	20:  "%g K level",
	21:  "lowest level > %g kg/m^3",
	22:  "highest level > %g kg/m^3",
	23:  "lowest level > %g Bq/m^3",
	24:  "highest level > %g Bg/m^3",
	25:  "highest level > %g dBZ",
	26:  "convective cloud layer base",
	27:  "convective clout layer top",
	28:  "reserved",
	29:  "reserved",
	30:  "specified radius from center of sun",
	31:  "solar photosphere",
	32:  "ionosphere D-region level",
	33:  "ionosphere E-region level",
	34:  "ionosphere F1-region level",
	35:  "ionosphere F2-region level",
	36:  "stratopause",
	37:  "reserved",
	38:  "reserved",
	39:  "reserved",
	40:  "reserved",
	41:  "reserved",
	42:  "reserved",
	43:  "reserved",
	44:  "reserved",
	45:  "reserved",
	46:  "reserved",
	47:  "reserved",
	48:  "reserved",
	49:  "reserved",
	50:  "reserved",
	51:  "reserved",
	52:  "reserved",
	53:  "reserved",
	54:  "reserved",
	55:  "reserved",
	56:  "reserved",
	57:  "reserved",
	58:  "reserved",
	59:  "reserved",
	60:  "reserved",
	61:  "reserved",
	62:  "reserved",
	63:  "reserved",
	64:  "reserved",
	65:  "reserved",
	66:  "reserved",
	67:  "reserved",
	68:  "reserved",
	69:  "reserved",
	70:  "reserved",
	71:  "reserved",
	72:  "reserved",
	73:  "reserved",
	74:  "reserved",
	75:  "reserved",
	76:  "reserved",
	77:  "reserved",
	78:  "reserved",
	79:  "reserved",
	80:  "reserved",
	81:  "reserved",
	82:  "reserved",
	83:  "reserved",
	84:  "reserved",
	85:  "reserved",
	86:  "reserved",
	87:  "reserved",
	88:  "reserved",
	89:  "reserved",
	90:  "reserved",
	91:  "reserved",
	92:  "reserved",
	93:  "reserved",
	94:  "reserved",
	95:  "reserved",
	96:  "reserved",
	97:  "reserved",
	98:  "reserved",
	99:  "reserved",
	100: "%g mb",
	101: "mean sea level",
	102: "%g m above mean sea level",
	103: "%g m above ground",
	104: "%g sigma level",
	105: "%g hybrid level",
	106: "%g m underground",
	107: "%g K isentropic level",
	108: "%g mb above ground",
	109: "PV=%g (Km^2/kg/s) surface",
	110: "reserved",
	111: "%g Eta level",
	112: "reserved",
	113: "%g logarithmic hybrid level",
	114: "snow level",
	115: "%g sigma height level",
	116: "reserved",
	117: "mixed layer depth",
	118: "%g hybrid height level",
	119: "%g hybrid pressure level",
	120: "reserved",
	121: "reserved",
	122: "reserved",
	123: "reserved",
	124: "reserved",
	125: "reserved",
	126: "reserved",
	127: "reserved",
	128: "reserved",
	129: "reserved",
	130: "reserved",
	131: "reserved",
	132: "reserved",
	133: "reserved",
	134: "reserved",
	135: "reserved",
	136: "reserved",
	137: "reserved",
	138: "reserved",
	139: "reserved",
	140: "reserved",
	141: "reserved",
	142: "reserved",
	143: "reserved",
	144: "reserved",
	145: "reserved",
	146: "reserved",
	147: "reserved",
	148: "reserved",
	149: "reserved",
	150: "%g generalized vertical height coordinate",
	151: "soil level %g",
	152: "sea-ice level",
	153: "reserved",
	154: "reserved",
	155: "reserved",
	156: "reserved",
	157: "reserved",
	158: "reserved",
	159: "reserved",
	160: "%g m below sea level",
	161: "%g m below water surface",
	162: "lake or river bottom",
	163: "bottom of sediment layer",
	164: "bottom of thermally active sediment layer",
	165: "bottom of sediment layer penetrated by thermal wave",
	166: "mixing layer",
	167: "bottom of root zone",
	168: "ocean model level %g",
	169: "ocean level %g (kg*m-3) density difference to near surface",
	170: "ocean level %g (K) pot. temperature difference to near surface",
	171: "ocean level %g (m*m/s) vertical eddy diffusivity difference from near surface",
	172: "mixed layer depth (delta rho=%g)",
	173: "reserved",
	174: "top surface of ice on sea, lake or river",
	175: "top surface of ice, und snow on sea, lake or river",
	176: "bottom surface ice on sea, lake or river",
	177: "deep soil",
	178: "reserved",
	179: "top surface of glacier ice and inland ice",
	180: "deep inland or glacier ice",
	181: "grid tile land fraction as a model surface",
	182: "grid tile water fraction as a model surface",
	183: "grid tile ice fraction on sea, lake or river as a model surface",
	184: "grid tile glacier ice and inland ice fraction as a model surface",
	185: "reserved",
	186: "reserved",
	187: "reserved",
	188: "reserved",
	189: "reserved",
	190: "reserved",
	191: "reserved",
}

// wgrib2NCEPLevels are NCEP's local level types 192-255.
var wgrib2NCEPLevels = [...]string{
	0:  "reserved",
	1:  "reserved",
	2:  "reserved",
	3:  "reserved",
	4:  "reserved",
	5:  "reserved",
	6:  "reserved",
	7:  "reserved",
	8:  "entire atmosphere (considered as a single layer)",
	9:  "entire ocean (considered as a single layer)",
	10: "reserved",
	11: "reserved",
	12: "highest tropospheric freezing level",
	13: "reserved",
	14: "grid scale cloud bottom level",
	15: "grid scale cloud top level",
	16: "reserved",
	17: "boundary layer cloud bottom level",
	18: "boundary layer cloud top level",
	19: "boundary layer cloud layer",
	20: "low cloud bottom level",
	21: "low cloud top level",
	22: "low cloud layer",
	23: "cloud ceiling",
	24: "effective layer top level %gm",
	25: "effective layer bottom level %gm",
	26: "effective layer %gm",
	27: "reserved",
	28: "planetary boundary layer",
	29: "layer between two hybrid levels",
	30: "middle cloud bottom level",
	31: "middle cloud top level",
	32: "middle cloud layer",
	33: "reserved",
	34: "reserved",
	35: "reserved",
	36: "reserved",
	37: "reserved",
	38: "reserved",
	39: "reserved",
	40: "high cloud bottom level",
	41: "high cloud top level",
	42: "high cloud layer",
	43: "%gC ocean isotherm",
	44: "layer between two depths below ocean surface",
	45: "bottom of ocean mixed layer",
	46: "bottom of ocean isothermal layer",
	47: "layer ocean surface and 26C ocean isothermal level",
	48: "ocean mixed layer",
	49: "%g in sequence",
	50: "convective cloud bottom level",
	51: "convective cloud top level",
	52: "convective cloud layer",
	53: "lowest level of the wet bulb zero",
	54: "maximum equivalent potential temperature level",
	55: "equilibrium level",
	56: "shallow convective cloud bottom level",
	57: "shallow convective cloud top level",
	58: "reserved",
	59: "deep convective cloud bottom level",
	60: "deep convective cloud top level",
	61: "lowest bottom level of supercooled liquid water layer",
	62: "highest top level of supercooled liquid water layer",
	63: "missing",
}

// wgrib2KMALevels are KMA's local level types 192-255.
var wgrib2KMALevels = [...]string{
	0:  "reserved",
	1:  "reserved",
	2:  "reserved",
	3:  "hybrid sigma pressure",
	4:  "Height from ground KFT",
	5:  "canopy",
	6:  "ICAO convective cloud top level",
	7:  "ICAO convective cloud base level",
	8:  "entire atmosphere (considered as a single layer)",
	9:  "entire ocean (considered as a single layer)",
	10: "reserved",
	11: "reserved",
	12: "highest tropospheric freezing level",
	13: "reserved",
	14: "grid scale cloud bottom level",
	15: "grid scale cloud top level",
	16: "reserved",
	17: "boundary layer cloud bottom level",
	18: "boundary layer cloud top level",
	19: "boundary layer cloud layer",
	20: "low cloud bottom level",
	21: "low cloud top level",
	22: "low cloud layer",
	23: "cloud ceiling",
	24: "reserved",
	25: "reserved",
	26: "reserved",
	27: "reserved",
	28: "planetary boundary layer",
	29: "layer between two hybrid levels",
	30: "middle cloud bottom level",
	31: "middle cloud top level",
	32: "middle cloud layer",
	33: "reserved",
	34: "reserved",
	35: "reserved",
	36: "reserved",
	37: "reserved",
	38: "reserved",
	39: "reserved",
	40: "high cloud bottom level",
	41: "high cloud top level",
	42: "high cloud layer",
	43: "%gC ocean isotherm",
	44: "layer between two depths below ocean surface",
	45: "bottom of ocean mixed layer",
	46: "bottom of ocean isothermal layer",
	47: "layer ocean surface and 26C ocean isothermal level",
	48: "ocean mixed layer",
	49: "%g in sequence",
	50: "convective cloud bottom level",
	51: "convective cloud top level",
	52: "convective cloud layer",
	53: "lowest level of the wet bulb zero",
	54: "maximum equivalent potential temperature level",
	55: "equilibrium level",
	56: "shallow convective cloud bottom level",
	57: "shallow convective cloud top level",
	58: "reserved",
	59: "deep convective cloud bottom level",
	60: "deep convective cloud top level",
	61: "lowest bottom level of supercooled liquid water layer",
	62: "highest top level of supercooled liquid water layer",
	63: "missing",
}
